'use client';
import { useState } from 'react';
import QRCode from 'react-qr-code';
import { useConnection } from 'wagmi';
import { configuredAddresses, configuredIncomeAddress, incomeAbi, tokenAbi } from '@/config/contracts';
import { claimIncome, claimableIds, useIncome } from '@/hooks/useIncome';
import { type Property } from '@/lib/brick';
import { amount, money } from '@/lib/format';
import { WalletHint } from '../DataBoundary';
import { useTransaction } from '../Transactions';

function dateLabel(timestamp: bigint) {
  return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(Number(timestamp) * 1_000));
}

export function PropertyIncome({ property, balance }: { property: Property; balance: bigint }) {
  const { address } = useConnection();
  const { run, canSign, busy } = useTransaction();
  const query = useIncome([property]);
  const [value, setValue] = useState('');
  const [reference, setReference] = useState('September 2026 rent');
  const [showQr, setShowQr] = useState(false);
  const income = query.data?.get(property.token.toLowerCase());
  const isCreator = address?.toLowerCase() === property.creator.toLowerCase();
  const ids = income ? claimableIds(income) : [];
  const hasHistory = !!income && (income.claimed > 0n || income.claimable > 0n);
  const noStake = !!address && property.owned === 0n && !hasHistory;
  // NEXT_PUBLIC_APP_URL should be a base URL reachable from the payer's phone (e.g. this
  // machine's LAN address, or a public tunnel) — "localhost" only resolves on this device.
  const configuredOrigin = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, '');
  const origin = configuredOrigin || (typeof window !== 'undefined' ? window.location.origin : '');
  const paymentParams = new URLSearchParams({ ...(value.trim() ? { amount: value.trim() } : {}), ...(reference.trim() ? { reference: reference.trim() } : {}) });
  const paymentUrl = origin ? `${origin}/properties/${property.id}/pay${paymentParams.size ? `?${paymentParams.toString()}` : ''}` : '';
  const isLocalUrl = !configuredOrigin && /^https?:\/\/(localhost|127\.0\.0\.1)(:|\/|$)/.test(origin);

  return <section className="section-space income-section" id="income">
    <div className="section-heading"><div><span className="eyebrow">PROPERTY PERFORMANCE</span><h2>Rental income</h2></div></div>
    {!configuredIncomeAddress ? <div className="notice">Rental income will be available after the income contract is connected.</div> : query.isError ? <div className="notice">Rental income is temporarily unavailable.</div> : <>
      <div className="income-summary-grid">
        <div className="panel income-highlight">
          <span className="eyebrow">GENERATED BY THIS PROPERTY</span>
          <p className="large-value">{income ? money(income.generated) : '—'}</p>
          <p className="muted">Total demonstration income paid to investors so far.{property.supply > 0n && income ? ` ${money(income.generated / property.supply)} per share.` : ''}</p>
        </div>
        {noStake ? <div className="panel">
          <span className="eyebrow">YOUR INCOME TO CLAIM</span>
          <h3>You need shares in this property to earn income</h3>
          <p className="muted">Buy shares in this property to start earning a proportional part of future rent payments.</p>
        </div> : <div className="panel">
          <span className="eyebrow">YOUR INCOME TO CLAIM</span>
          <p className="large-value">{income ? money(income.claimable) : '—'}</p>
          <button disabled={!canSign || ids.length === 0} onClick={() => void run(async send => {
            const claimed = income!.claimable;
            await claimIncome(send, ids);
            return `${money(claimed)} added to your demo balance.`;
          })}>Claim</button>
          <dl className="summary-lines"><div><dt>Already claimed</dt><dd>{income ? money(income.claimed) : '—'}</dd></div></dl>
        </div>}
      </div>
      <WalletHint />
      {isCreator && <div className="panel income-deposit">
        <div><span className="eyebrow">OWNER DEMO</span><h3>Record a rent payment</h3><p className="muted">Deposit fictional mBRL and it is allocated to each investor according to their ownership at confirmation.</p></div>
        <label>Amount (mBRL)<input value={value} onChange={event => setValue(event.target.value)} inputMode="decimal" placeholder="10000" disabled={busy} /><small>Available demo balance: {money(balance)}</small></label>
        <label>Reference<input value={reference} onChange={event => setReference(event.target.value)} maxLength={200} disabled={busy} /></label>
        <button disabled={!canSign} onClick={() => void run(async send => {
          const incomeAmount = amount(value);
          if (incomeAmount > balance) throw new Error('Insufficient demo balance. Add demo funds using the wallet menu.');
          await send(configuredAddresses!.currency, tokenAbi, 'approve', [configuredIncomeAddress!, incomeAmount], '1/2 Authorizing rent payment');
          await send(configuredIncomeAddress!, incomeAbi, 'createDistribution', [property.token, incomeAmount, reference.trim()], '2/2 Recording rent payment');
          setValue('');
          return 'Rent payment recorded. Investors can now claim their share.';
        })}>Record payment</button>
        <p className="muted">Or let the tenant pay directly: generate a QR code for this amount and reference below. No wallet needed on their end.</p>
        <button type="button" className="button-secondary" onClick={() => setShowQr(!showQr)}>{showQr ? 'Hide payment QR code' : 'Share as QR code'}</button>
        {showQr && <div className="qr-panel">
          {isLocalUrl && <p className="notice">This link points to {origin}, which only works on this device. Set NEXT_PUBLIC_APP_URL to a URL reachable from a phone (your machine&rsquo;s LAN address or a public tunnel) and reload before sharing the QR code.</p>}
          <QRCode value={paymentUrl} size={168} />
          <p className="muted">Anyone who scans this can pay this property&rsquo;s rent instantly, with no wallet or app required. The amount is split among every shareholder automatically.</p>
          <input readOnly value={paymentUrl} onFocus={event => event.target.select()} />
        </div>}
      </div>}
      <div className="income-history">
        <h3>Payment history</h3>
        {income?.distributions.length ? [...income.distributions].reverse().map(distribution => <article className="income-row panel" key={distribution.id.toString()}>
          <div><strong>{distribution.memo || 'Rental income'}</strong><p className="muted">{dateLabel(distribution.createdAt)}</p></div>
          <dl className="summary-lines income-row-stats"><div><dt>Total paid</dt><dd>{money(distribution.amount)}</dd></div><div><dt>Your part</dt><dd>{money(distribution.yourShare)}</dd></div></dl>
          <span className={`status ${distribution.claimed ? 'status-claimed' : distribution.yourShare > 0n ? 'status-available' : ''}`}>{distribution.claimed ? 'Claimed' : distribution.yourShare > 0n ? 'Available' : '—'}</span>
        </article>) : <div className="empty-state"><span className="empty-icon" aria-hidden="true">↗</span><h3>No rent payments yet</h3><p>Rent payments will appear here once the owner records one.</p></div>}
      </div>
    </>}
  </section>;
}
